# Generated by Django 3.2.11 on 2022-01-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_code', models.IntegerField()),
                ('security_name', models.CharField(max_length=100)),
                ('close', models.FloatField()),
                ('market_cap', models.FloatField()),
            ],
        ),
    ]
